# Generated by Django 5.0.6 on 2024-06-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
    ]
