# Generated by Django 5.0.6 on 2024-06-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estrella', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('stock_talla_s', models.PositiveIntegerField(default=0)),
                ('stock_talla_m', models.PositiveIntegerField(default=0)),
                ('stock_talla_l', models.PositiveIntegerField(default=0)),
                ('stock_talla_xl', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fotografia', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
