# Generated by Django 5.0.6 on 2024-06-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estrella', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url_compra',
            field=models.URLField(blank=True, null=True),
        ),
    ]
