# Generated by Django 5.0.6 on 2024-07-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estrella', '0003_producto_url_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url_compra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
