# Generated by Django 5.0.6 on 2024-07-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estrella', '0004_usuario_es_admin_alter_producto_url_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_admin',
        ),
    ]
